<?

namespace backend\modules\orderPropertyManagment\models;

use backend\models\Tags;
use common\models\Config;
use common\models\WbpActiveRecord;

class OrderPropertyManagment extends WbpActiveRecord{

    public static function tableName()
    {
        return '{{%contact}}';
    }

    public function rules()
    {
        return [
            [['fname', 'phone', 'email', 'type', 'message'], 'safe', 'on' => 'edit']
        ];
    }

    public function getAnswers()
    {
        return $this->hasMany(OrderPropertyManagmentAnswers::className(), ['contact_id', 'id']);
    }

//    public function beforeSave($insert)
//    {
//        \Yii::$app->mailer->compose(['text'])
//            ->setFrom([Config::getParameter('email') => Config::getParameter('title')])
//            ->setTo([Config::getParameter('email') => Config::getParameter('title')])
//            ->setSubject('New message from ' . $this->email )
//            ->setCharset('UTF-8')
//            ->setHtmlBody($this->fname.' '.$this->lname.'<br>Телефон: '. $this->phone.'<br> Тема: '.$this->subject."<br>". $this->message . "<br><br><br><br>
//            View the <a href='" . \Yii::$app->urlManager->createAbsoluteUrl('admin/contacts') . "'>message</a>")
//            ->send();
//        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
//    }


}