<?php
/**
 * Created by PhpStorm.
 ** User: TrickTrick alexeymarkov.x7@gmail.com 
 *** Date: 26.05.2015 
 **** Time: 14:18
 */

namespace backend\modules\social\models;

use common\models\WbpActiveRecord;

class SocialDB extends WbpActiveRecord
{

    public static
        $social = [
        'linkedin'              => 'Linkedin link',
        'facebook'              => 'Facebook',
        'twitter'               => 'Twitter link',
        'youtube'               => 'Youtube',
        'instagram'             => 'Instagram',
        'facebook_app_id'       => 'Facebook app ID',
        'facebook_api_secret'   => 'Facebook API secret',
        'twitter_api_key'       => 'Twitter API key',
        'twitter_api_secret'    => 'Twitter API secret',
        'facebook_widget'       => 'Facebook widget',
        'twitter_widget'        => 'Twitter widget',
        'pinterest'             => 'Pinterest link',
        'vk'                    => 'Vkontakte',
        'skype'                 => 'Skype',
        'google_plus'           => 'Google+'
        ];

    public static function tableName()
    {
        return '{{%config}}'; // TODO: Change the autogenerated stub
    }

    public function getLabel()
    {
        return self::$social[$this->name];
    }

}
