<?php
namespace backend\modules\partners\models;

use common\models\WbpActiveRecord;
use yii\helpers\StringHelper;
use yii\helpers\Url;

/**
 * Class Sweepstakes
 * @package backend\modules\sweepstakes\models
 */
class Partners extends WbpActiveRecord
{

    public static $imageTypes = ['Partners'];

    public static function tableName()
    {
        return '{{%partners}}';
    }

    public function rules()
    {
        return [
            [['first_name', 'last_name', 'position', 'phone', 'email', 'status', 'href', 'sort'], 'safe', 'on' => [WbpActiveRecord::ADMIN_ADD_SCENARIO, WbpActiveRecord::ADMIN_EDIT_SCENARIO]],
            [['first_name', 'last_name', 'status',], 'required', 'on' => [WbpActiveRecord::ADMIN_ADD_SCENARIO, WbpActiveRecord::ADMIN_EDIT_SCENARIO]],
        ];
    }

    public function getDescription($symbols = 150)
    {
        $out = $this->description;
        if ($this->short_description) {
            $out = $this->short_description;
        }


        return StringHelper::truncate($out, $symbols);
    }

    public static function findByHref($href)
    {
        return self::find()
            ->where(['href' => $href]);
    }

    public static function findById($id)
    {
        return self::find()->where(['id' => $id])->one();
    }

    public static function findByMonthYearDay($month,$year,$day){
        $month=sprintf("%02d",$month);
        $day=sprintf("%02d",$day);
        $startDate=$year.'-'.$month.'-'.$day.' 00:00:00';
        $stopDate=$year.'-'.$month.'-'.$day.' 23:59:59';
        return self::find()->Where(['status'=>'1'])->andWhere(['>=','date',$startDate])->andWhere(['<=','date',$stopDate]);
    }

    public function getUrl(){
        return Url::to(['partners/view', 'href'=>$this->href]);
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'first_name'    => 'Имя',
            'last_name'     => 'Фамилия',
            'position'      => 'Должность',
            'phone'         => 'Телефон',
            'email'         => 'E-mail',
            'href'          => 'Ссылка',
            'status'        => \Yii::t('admin', 'status'),
        ];
    }

}