<?php

namespace frontend\models;

use yii\helpers\ArrayHelper;

class Contacts extends \backend\modules\contacts\models\Contacts
{

    const FRONTEND_ADD_SCENARIO = 'frontend';

    public $return;

    public function init()
    {
        $this->return=$_SERVER['REQUEST_URI'];
        parent::init();
    }

    public function rules()
    {

        $rules = [
            //make request part
            [['fname', 'email', 'phone', 'type', 'message'], 'safe', 'on' => self::FRONTEND_ADD_SCENARIO],
            [['fname', 'email'], 'required', 'message' => 'Это обязательное поле', 'on' => self::FRONTEND_ADD_SCENARIO],
            ['email', 'email', 'message' => 'Введите валидный email (пример "admin@google.com")', 'on' => self::FRONTEND_ADD_SCENARIO],

            [['fname', 'message'], 'string', 'on' => self::FRONTEND_ADD_SCENARIO],
        ];

        return ArrayHelper::merge(parent::rules(), $rules);
    }

    public function attributeLabels()
    {
        return [
            'fname' => 'Имя',
            'phone' => 'Телефон',
            'email' => 'Email',
            'message' => 'Комментарии или пожелания',
        ];
    }

    public function beforeSave($insert)
    {

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
