<?php

namespace backend\modules\adverts\models;

use backend\modules\adverts\models\ObjectTypes;
use common\models\WbpActiveRecord;
use yii\helpers\Url;
use backend\modules\categories\models\Category;
use common\models\User;


class Router extends WbpActiveRecord
{

    public static $seoKey = 'adverts';
    public static $imageTypes = ['adverts'];
    public static $videoTypes = ['video'];

    public static function tableName()
    {
        return '{{%adverts}}';
    }

    public function rules()
    {
        return [
            [[
                'category_id',

                'object_type_id'


            ], 'safe'],
            [['category_id','object_type_id'], 'required', 'message' => 'Это обязательное поле'],
            //[['price', 'kitchen', 'living_space', 'total_area', 'prepayment', 'deposit','price_dollar','price_euro'], 'integer', 'message' => 'Введите число'],
        ];
    }


    public function attributeLabels()
    {
        return [
            'title' => \Yii::t('admin', 'title'),
            'title_ru' => \Yii::t('admin', 'title'),
            'href' => \Yii::t('admin', 'href'),
            'description' => \Yii::t('admin', 'description'),
            'description_ru' => \Yii::t('admin', 'description'),
            'status' => \Yii::t('admin', 'status'),
            'parent' => \Yii::t('admin', 'parent'),
            'moisture' => \Yii::t('admin', 'moisture'),
            'moisture_ru' => \Yii::t('admin', 'moisture'),
            'purity' => \Yii::t('admin', 'purity'),
            'purity_ru' => \Yii::t('admin', 'purity'),
            'test_weight' => \Yii::t('admin', 'test_weight'),
            'test_weight_ru' => \Yii::t('admin', 'test_weight'),
            'grain_admixture' => \Yii::t('admin', 'grain_admixture'),
            'grain_admixture_ru' => \Yii::t('admin', 'grain_admixture'),
            'min_order' => \Yii::t('admin', 'min_order'),
            'min_order_ru' => \Yii::t('admin', 'min_order'),
            'packing' => \Yii::t('admin', 'packing'),
            'floor' => \Yii::t('admin', 'Этаж'),
            'category_id' => \Yii::t('admin', 'Category'),
            'building_type' => \Yii::t('admin', 'Тип здания'),
            'nearness_id' => \Yii::t('admin', 'Близость к морю'),
            'repairs' => \Yii::t('admin', 'Ремонт'),
            'city_id' => \Yii::t('admin', 'Город'),
            'address' => \Yii::t('admin', 'Адрес'),
            'object_type_id' => \Yii::t('admin', 'Тип Объекта'),
            'price' => \Yii::t('admin', 'Цена (в рублях)'),
            'price_dollar' => \Yii::t('admin', 'Цена (в долларах)'),
            'price_euro' => \Yii::t('admin', 'Цена (в Евро)'),
            'total_area' => \Yii::t('admin', 'Общая площадь'),
            'living_space' => \Yii::t('admin', 'Жилая площадь'),
            'balconies' => \Yii::t('admin', 'Балконы'),
            'exclusive' => \Yii::t('admin', 'Эксклюзивная продажа'),
            'kitchen' => \Yii::t('admin', 'Площадь кухни'),
            'furniture' => \Yii::t('admin', 'Мебель'),
            'windows' => \Yii::t('admin', 'Окна'),
            'lift' => \Yii::t('admin', 'Лифт'),
            'comfort' => \Yii::t('admin', 'Удобства'),
            'deposit' => \Yii::t('admin', 'Задаток  (в рублях)'),
            'prepayment' => \Yii::t('admin', 'Предоплата (месяцев)'),
            'reserve' => \Yii::t('admin', 'Зарезервировано'),
        ];
    }

    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'category_id']);
    }


    public function getUrl($absolute = false)
    {
        return Url::to(['adverts/view', 'href' => $this->href], $absolute);
    }

    public function hasChildren()
    {
        return $this->getChildren()->count();
    }

    public function getChildren()
    {
        return self::find()->where(['status' => 1, 'parent' => $this->id])->orderBy(['sort' => SORT_ASC]);
    }
    public function getObjectType()
    {
        return $this->hasOne(ObjectTypes::className(), ['object_type_id' => 'id']);
    }
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    public function getRooms()
    {
        return $this->hasOne(Rooms::className(), ['id' => 'rooms_id']);
    }
    public function getCity()
    {
        return $this->hasOne(\backend\modules\regions\models\Regions::className(), ['id' => 'city_id']);
    }

    public function afterSave($insert, $changedAttributes)
    {


        return parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}